news_sites:
  eluniversal:
    url: http://www.eluniversal.com.mx
    queries:
      homepage_article_links: ".field-content a"
      article_title: ".Encabezado-Articulo h1"
      article_body: ".field-name-body p"
  elpais:
    url: https://elpais.com
    queries:
      homepage_article_links: ".headline a"
      article_title: "#article_header h1"
      article_body: ".article_body p"
  eltiempo:
    url: https://www.eltiempo.com
    queries:
      homepage_article_links: ".title-container a"
      article_title: "h1.titulo"
      article_body: "p.contenido"
